name: magic_dropdown_search
description: "A flutter package for a dropdown search with dynamic data from Api"
version: 0.0.6
homepage: https://github.com/mzzznn
repository: https://github.com/mzzznn/magic_dropdown_search

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
